simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/',include('groups.urls',namespace = 'groups')),
    path('posts/',include('posts.urls',namespace = 'posts')),

]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

  </head>

  <body>
    <div class="container-fluid">

    <nav class="navbar navbar-expand-lg bg   ">
    <a class="navbar-brand" href="{% url 'home' %}">Star Social</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'posts:create' %}">Post</a>
        <a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a>
        <a class="nav-item nav-link" href="{% url 'groups:create' %}">Create Group</a>
        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a>
        <a class="nav-item nav-link" href="{% url 'signup' %}">Sign Up</a>
        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
        {% endif %}
      </div>
    </div>
  </nav>

  </div>

    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

  </body>
  <script src="{% static 'simplesocial/js/master.js' %}" type="text/javascript" ></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>

simplesocial/templates/index.html
{% extends 'base.html' %}

{%  block content %}
<h1>Welcome to Star Social</h1>
<br>
<br>
<h4>The best community for all things on outer space!</h4>
<h4>Login or Sign-up for free to get started!</h4>

{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>



</div>




{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}